def proto_args(parser, parents):
    rpc_parser = parser.add_parser("rpc", help="own stuff using MSRPC", conflict_handler="resolve", parents=parents)
    rpc_parser.add_argument("-H", "--hash", metavar="HASH", dest="hash", nargs="+", default=[], help="NTLM hash(es) or file(s) containing NTLM hashes")
    rpc_parser.add_argument("--port", type=int, default=135, help="RPC port (default: 135)")
    rpc_parser.add_argument("--rpc-timeout", help="RPC connection timeout", type=int, default=2)

    dgroup = rpc_parser.add_mutually_exclusive_group()
    dgroup.add_argument("-d", metavar="DOMAIN", dest="domain", default=None, type=str, help="Domain to authenticate to")
    dgroup.add_argument("--local-auth", action="store_true", help="Authenticate locally to each target")

    info_group = rpc_parser.add_argument_group("Server/Domain Information")
    info_group.add_argument("--server-info", action="store_true", help="Server info (srvinfo)")
    info_group.add_argument("--enum-domains", action="store_true", help="Enumerate domains (enumdomains)")
    info_group.add_argument("--enum-trusts", action="store_true", help="Enumerate trusted domains (enumtrust)")
    info_group.add_argument("--domain-info", action="store_true", help="Domain info (querydominfo)")
    info_group.add_argument("--pass-pol", action="store_true", help="Password policy (getdompwinfo)")

    user_group = rpc_parser.add_argument_group("User Enumeration")
    user_group.add_argument("--users", action="store_true", help="Enumerate users (enumdomusers)")
    user_group.add_argument("--querydispinfo", action="store_true", help="Query display info (querydispinfo)")
    user_group.add_argument("--rid-brute", nargs="?", type=int, const=4000, metavar="MAX_RID", help="RID cycling enumeration")
    user_group.add_argument("--user", metavar="RID_OR_NAME", type=str, help="Query user by RID or name (queryuser)")
    user_group.add_argument("--user-pass-pol", metavar="RID", type=str, help="User password info (getusrdompwinfo)")
    user_group.add_argument("--lookup-names", metavar="NAMES", type=str, help="Lookup names (lookupnames)")

    group_group = rpc_parser.add_argument_group("Group Enumeration")
    group_group.add_argument("--groups", action="store_true", help="Enumerate domain groups (enumdomgroups)")
    group_group.add_argument("--group", metavar="RID_OR_NAME", type=str, help="Query group by RID or name (querygroup)")
    group_group.add_argument("--local-groups", action="store_true", help="Enumerate alias groups (enumalsgroups)")

    share_group = rpc_parser.add_argument_group("Share Enumeration")
    share_group.add_argument("--shares", action="store_true", help="Enumerate shares (netshareenumall)")
    share_group.add_argument("--share", metavar="SHARE", type=str, help="Share info (netsharegetinfo)")
    share_group.add_argument("--sessions", action="store_true", help="Enumerate sessions")
    share_group.add_argument("--connections", action="store_true", help="Enumerate connections")

    lsa_group = rpc_parser.add_argument_group("LSA Operations")
    lsa_group.add_argument("--lsa-query", action="store_true", help="LSA query (lsaquery)")
    lsa_group.add_argument("--lsa-lookup-sids", metavar="SIDS", type=str, help="Lookup SIDs (lookupsids)")
    lsa_group.add_argument("--lsa-lookup-names", metavar="NAMES", type=str, help="Lookup names via LSA")
    lsa_group.add_argument("--lsa-enum-accounts", action="store_true", help="Enumerate SIDs (lsaenumsid)")
    lsa_group.add_argument("--lsa-enum-privileges", action="store_true", help="Enumerate privileges (enumprivs)")
    lsa_group.add_argument("--lsa-enum-account-rights", metavar="SID", type=str, help="Account rights (lsaenumacctrights)")
    lsa_group.add_argument("--lsa-create-account", metavar="SID", type=str, help="Create LSA account (lsacreateaccount)")
    lsa_group.add_argument("--lsa-query-security", action="store_true", help="Query LSA security object (lsaquerysecobj)")

    sid_group = rpc_parser.add_argument_group("SID/SAM Operations")
    sid_group.add_argument("--sid-lookup", metavar="SID", type=str, help="Lookup SID to name")
    sid_group.add_argument("--sam-lookup", nargs=2, metavar=("domain|builtin", "NAMES"), help="SAM lookup (samlookupnames)")
    sid_group.add_argument("--lookup-domain", metavar="DOMAIN", type=str, help="Domain lookup (lookupdomain)")

    mgmt_group = rpc_parser.add_argument_group("User/Group Management")
    mgmt_group.add_argument("--create-user", metavar="USER:PASS", type=str, help="Create user (createdomuser + setuserinfo2)")
    mgmt_group.add_argument("--delete-user", metavar="USER", type=str, help="Delete user (deletedomuser)")
    mgmt_group.add_argument("--enable-user", metavar="USER", type=str, help="Enable user account (setuserinfo2)")
    mgmt_group.add_argument("--disable-user", metavar="USER", type=str, help="Disable user account (setuserinfo2)")
    mgmt_group.add_argument("--set-user-info", nargs=3, metavar=("USER", "CLASS", "VALUE"), help="Set user info (setuserinfo2). Classes: fullname, description, comment, homedir, homedrive, script, profile, workstations, control, expires, primary-group, parameters, name (newuser:newfullname), logonhours (all/none/hex), preferences (country:codepage)")
    mgmt_group.add_argument("--change-password", metavar="USER:OLD:NEW", type=str, help="Change password with old password (chgpasswd)")
    mgmt_group.add_argument("--reset-password", metavar="USER:NEWPASS", type=str, help="Admin reset password (setuserinfo2)")
    mgmt_group.add_argument("--create-group", metavar="GROUP", type=str, help="Create group (createdomgroup)")
    mgmt_group.add_argument("--delete-group", metavar="GROUP", type=str, help="Delete group (deletedomgroup)")
    mgmt_group.add_argument("--add-to-group", metavar="USER:GROUP", type=str, help="Add user to group")
    mgmt_group.add_argument("--remove-from-group", metavar="USER:GROUP", type=str, help="Remove user from group")

    return parser
