name: Lint Python code with ruff
# Caching source: https://gist.github.com/gh640/233a6daf68e9e937115371c0ecd39c61?permalink_comment_id=4529233#gistcomment-4529233

on:
  push:
  workflow_dispatch:
  pull_request_review:
    types: [submitted]

jobs:
  lint:
    runs-on: ubuntu-latest
    if:
      github.event_name == 'push' || github.event.review.state == 'APPROVED' || github.event_name == 'workflow_dispatch'

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: true
      - name: Set up Python
        run: uv python install 3.13
      - name: Run ruff
        run: |
          uvx ruff@0.11.0 --version
          uvx ruff@0.11.0 check . --preview
